### ISSUE TITLE
Static analysis says

### ISSUE THREAD

**Issue by szepeviktor** [WP-API/jwt-auth#14]
Hello! This is PHPStan config

```yaml
# Start command: composer require --dev szepeviktor/phpstan-wordpress && vendor/bin/phpstan analyze

includes:
    - vendor/phpstan/phpstan/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    paths:
        - %currentWorkingDirectory%/wp-includes/
    autoload_directories:
        - %currentWorkingDirectory%/wp-includes/
        - %currentWorkingDirectory%/wp-admin/includes/
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters invoked with [34567] parameters, 2 required\.$#'
        - '#^Function current_user_can invoked with 2 parameters, 1 required\.$#'

```
